#!/usr/bin/env bash
# bootstrap.sh — First-time bootstrap for basecoat-sheen consumer repos
#
# Run this ONCE from inside your repo before anything else.
# Downloads sync.sh, creates a starter .sheen.yml, and runs the initial sync.
#
# ONE-LINER USAGE (copy and run in your repo root):
#   bash <(curl -fsSL https://raw.githubusercontent.com/ivegamsft/sheen/main/bootstrap.sh)
#
# OR download first (safer):
#   curl -fsSL https://raw.githubusercontent.com/ivegamsft/sheen/main/bootstrap.sh -o bootstrap.sh
#   bash bootstrap.sh
#   rm bootstrap.sh   # optional — clean up

set -euo pipefail

SOURCE="${SHEEN_SOURCE:-https://github.com/IBuySpy-Shared/basecoat-sheen.git}"
REF="${SHEEN_REF:-main}"
PUBLIC_RAW="https://raw.githubusercontent.com/ivegamsft/sheen/main"

cyan()  { printf '\033[36m  bootstrap: %s\033[0m\n' "$1"; }
green() { printf '\033[32m  ✅ %s\033[0m\n' "$1"; }
yellow(){ printf '\033[33m  ⚠️  %s\033[0m\n' "$1"; }

echo ""
echo -e "\033[34mbasecoat-sheen bootstrap\033[0m"
echo -e "\033[34m========================\033[0m"

# Verify we're in a git repo
if ! command -v git >/dev/null 2>&1; then
  echo "error: git is required. Install from https://git-scm.com"; exit 1
fi
REPO_ROOT="$(git rev-parse --show-toplevel)"
green "repo root: $REPO_ROOT"

# Prefer curl, fall back to wget
download() {
  local url="$1" dest="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$dest"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$dest" "$url"
  else
    echo "error: curl or wget is required"; exit 1
  fi
}

# Download sync.sh if not present
SYNC_SH="$REPO_ROOT/sync.sh"
if [ ! -f "$SYNC_SH" ]; then
  cyan "downloading sync.sh from $PUBLIC_RAW …"
  download "$PUBLIC_RAW/sync.sh" "$SYNC_SH"
  chmod +x "$SYNC_SH"
  green "sync.sh downloaded"
else
  green "sync.sh already present"
fi

# Download sync.ps1 if not present (for cross-platform consumer repos)
SYNC_PS="$REPO_ROOT/sync.ps1"
if [ ! -f "$SYNC_PS" ]; then
  cyan "downloading sync.ps1 …"
  download "$PUBLIC_RAW/sync.ps1" "$SYNC_PS"
  green "sync.ps1 downloaded"
fi

# Create starter .sheen.yml if not present
SHEEN_YML="$REPO_ROOT/.sheen.yml"
if [ ! -f "$SHEEN_YML" ]; then
  cyan "creating starter .sheen.yml …"
  cat > "$SHEEN_YML" <<EOF
# .sheen.yml — basecoat-sheen consumer configuration
# Generated by bootstrap.sh. Commit this file.
# Docs: https://ivegamsft.github.io/sheen/guides/sheen-yml/

source: ${SOURCE}
ref: "${REF}"

# Uncomment and edit to limit which assets are synced.
# Empty list [] = sync none. Omit key = sync all (default).
# Asset names without file extension (e.g. 'design-tokens' not 'design-tokens.md')
#
# skills:
#   - design-tokens
#   - color-system
#   - typography
#   - accessibility-audit
#   - sheen-onboard        # onboarding assistant — include this!
# agents:
#   - design-system-architect
#   - accessibility-auditor
# instructions: []
# prompts: []

# Uncomment to build CSS/JS token output after every sync:
# materialize_tokens: true

# Uncomment to generate DESIGN.md (AI-readable design context):
# generate_design_md: true
EOF
  green ".sheen.yml created — edit it to customise your allow-list, then re-run sync"
else
  green ".sheen.yml already present"
fi

# Run sync
cyan "running sync …"
echo ""
bash "$SYNC_SH"

echo ""
echo -e "\033[32mbasecoat-sheen bootstrap complete!\033[0m"
echo ""
echo -e "\033[33mNext steps:\033[0m"
echo "  1. Review .sheen.yml and customise your allow-lists."
echo "  2. Commit the synced files:"
echo "       git add .sheen.yml .sheen/manifest.json .github/ sheen/"
echo "       git commit -m 'chore: integrate basecoat-sheen'"
echo "  3. Reset Copilot context (REQUIRED for skills to appear):"
echo "     • CLI:    exit  then  gh copilot"
echo "     • VS Code: Ctrl+Shift+P → Developer: Reload Window"
echo "     • JetBrains: restart editor"
echo "  4. Type / in Copilot Chat and confirm sheen-onboard appears."
echo "  5. Invoke: /sheen-onboard run the full onboarding lifecycle"
echo ""
echo "Docs: https://ivegamsft.github.io/sheen/guides/consumer-lifecycle/"
