#!/usr/bin/env pwsh
# bootstrap.ps1 — First-time bootstrap for basecoat-sheen consumer repos
#
# Run this ONCE from inside your repo before anything else.
# Downloads sync.ps1, creates a starter .sheen.yml, and runs the initial sync.
#
# ONE-LINER USAGE (copy and run in your repo root):
#   pwsh -c "iex (iwr https://raw.githubusercontent.com/ivegamsft/sheen/main/bootstrap.ps1).Content"
#
# OR download first (safer):
#   Invoke-WebRequest https://raw.githubusercontent.com/ivegamsft/sheen/main/bootstrap.ps1 -OutFile bootstrap.ps1
#   pwsh bootstrap.ps1
#   Remove-Item bootstrap.ps1   # optional — clean up

param(
    # Source repo URL (override if using a private mirror)
    [string]$Source = 'https://github.com/ivegamsft/sheen.git',
    # Ref to pin to (tag, branch, or SHA). 'main' for latest.
    [string]$Ref = 'main',
    # Skip the interactive .sheen.yml prompts and use minimal defaults
    [switch]$Silent
)

$ErrorActionPreference = 'Stop'

$PublicRaw = 'https://raw.githubusercontent.com/ivegamsft/sheen/main'

function Write-Step([string]$Msg) { Write-Host "  bootstrap: $Msg" -ForegroundColor Cyan }
function Write-OK([string]$Msg)   { Write-Host "  ✅ $Msg" -ForegroundColor Green }
function Write-Warn([string]$Msg) { Write-Host "  ⚠️  $Msg" -ForegroundColor Yellow }

Write-Host ""
Write-Host "basecoat-sheen bootstrap" -ForegroundColor Blue
Write-Host "========================" -ForegroundColor Blue

# ── Verify we're inside a git repo ───────────────────────────────────────────
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    throw "git is required. Install from https://git-scm.com"
}
$repoRoot = git rev-parse --show-toplevel 2>$null
if (-not $repoRoot) {
    throw "bootstrap.ps1 must be run from inside a git repository."
}
Write-OK "repo root: $repoRoot"

# ── Download sync.ps1 if not present ─────────────────────────────────────────
$syncScript = Join-Path $repoRoot 'sync.ps1'
if (-not (Test-Path $syncScript)) {
    Write-Step "downloading sync.ps1 from $PublicRaw …"
    Invoke-WebRequest -Uri "$PublicRaw/sync.ps1" -OutFile $syncScript -UseBasicParsing
    Write-OK "sync.ps1 downloaded"
} else {
    Write-OK "sync.ps1 already present"
}

# ── Download sync.sh if not present ──────────────────────────────────────────
$syncSh = Join-Path $repoRoot 'sync.sh'
if (-not (Test-Path $syncSh)) {
    Write-Step "downloading sync.sh …"
    Invoke-WebRequest -Uri "$PublicRaw/sync.sh" -OutFile $syncSh -UseBasicParsing
    Write-OK "sync.sh downloaded"
}

# ── Create starter .sheen.yml if not present ─────────────────────────────────
$sheenYml = Join-Path $repoRoot '.sheen.yml'
if (-not (Test-Path $sheenYml)) {
    Write-Step "creating starter .sheen.yml …"

    $sheenYmlContent = @"
# .sheen.yml — basecoat-sheen consumer configuration
# Generated by bootstrap.ps1. Commit this file.
# Docs: https://ivegamsft.github.io/sheen/guides/sheen-yml/

source: $Source
ref: "$Ref"

# Uncomment and edit to limit which assets are synced.
# Empty list [] = sync none. Omit key = sync all (default).
# Asset names without file extension (e.g. 'design-tokens' not 'design-tokens.md')
#
# skills:
#   - design-tokens
#   - color-system
#   - typography
#   - accessibility-audit
#   - sheen-onboard        # onboarding assistant — include this!
# agents:
#   - design-system-architect
#   - accessibility-auditor
# instructions: []
# prompts: []

# Uncomment to build CSS/JS token output after every sync:
# materialize_tokens: true

# Uncomment to generate DESIGN.md (AI-readable design context):
# generate_design_md: true
"@

    Set-Content -LiteralPath $sheenYml -Value $sheenYmlContent -Encoding utf8
    Write-OK ".sheen.yml created — edit it to customise your allow-list, then re-run sync"
} else {
    Write-OK ".sheen.yml already present"
}

# ── Run sync ──────────────────────────────────────────────────────────────────
Write-Step "running sync …"
Write-Host ""
& pwsh -NonInteractive -File $syncScript
if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) {
    throw "sync failed (exit $LASTEXITCODE). Check the output above."
}

Write-Host ""
Write-Host "basecoat-sheen bootstrap complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Review .sheen.yml and customise your allow-lists."
Write-Host "  2. Commit the synced files:"
Write-Host "       git add .sheen.yml .sheen/manifest.json .github/ sheen/"
Write-Host "       git commit -m 'chore: integrate basecoat-sheen'"
Write-Host "  3. Reset Copilot context (REQUIRED for skills to appear):"
Write-Host "     • CLI:    exit  then  gh copilot"
Write-Host "     • VS Code: Ctrl+Shift+P → Developer: Reload Window"
Write-Host "     • JetBrains: restart editor"
Write-Host "  4. Type / in Copilot Chat and confirm sheen-onboard appears."
Write-Host "  5. Invoke: /sheen-onboard run the full onboarding lifecycle"
Write-Host ""
Write-Host "Docs: https://ivegamsft.github.io/sheen/guides/consumer-lifecycle/"
