#!/usr/bin/env python3
"""Real sync/Git integration; fixture builder is not DTCG validation.

If powershell-yaml is unavailable, only the three fixture config scalars are
decoded by a strict test-local shim. Sync, ignore decisions and Git are real.
All fixtures (including sync clone TEMP/TMP/TMPDIR) stay under repository dist/.
"""
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import unittest
import uuid

ROOT = Path(__file__).resolve().parent.parent
BASH = r"C:\Program Files\Git\bin\bash.exe" if os.name == "nt" else "bash"
OUTPUTS = tuple(f"dist/tokens/{name}" for name in
                ("sheen.css", "sheen.js", "sheen.esm.js", "sheen.d.ts"))
RULES = "".join(f"/{path}\n" for path in OUTPUTS).encode()
SENTINELS = ("dist/app.txt", "dist/tokens/app.js", "dist/tokens/sheen.css.map",
             "app/dist/tokens/sheen.css", ".agents/skills/other/SKILL.md",
             "sheen/tokens/custom.json", "sheen/templates/custom.txt", ".sheen/consumer-state")


def generated(path, body=None):
    name = Path(path).name
    header = (f"/* {name} — generated by scripts/build-tokens.ps1; do not hand-edit */"
              if name == "sheen.css" else
              f"// {name} — generated by scripts/build-tokens.ps1; do not hand-edit")
    return header + "\n" + (body if body is not None else f"regenerated {name}\n")


def index_entries(repo):
    return {line.split("\t", 1)[1]: line.split("\t", 1)[0]
            for line in git(repo, "ls-files", "--stage").splitlines()}


def run(args, cwd, env=None, check=True):
    result = subprocess.run(args, cwd=cwd, env=env, capture_output=True,
                            text=True, encoding="utf-8", errors="replace", timeout=90)
    if check and result.returncode:
        raise AssertionError(f"{args}: exit {result.returncode}\n{result.stdout}{result.stderr}")
    return result


def git(repo, *args):
    return run(["git", "-C", str(repo), *args], ROOT).stdout


def write(root, name, content):
    path = root / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content if isinstance(content, bytes) else content.encode())


def remove_fixture(root):
    def retry(function, path, error):
        if not isinstance(error[1], PermissionError):
            raise error[1]
        os.chmod(path, stat.S_IWRITE | stat.S_IREAD)
        function(path)
    shutil.rmtree(root, onerror=retry)


def init(repo):
    repo.mkdir()
    git(repo, "init", "--quiet", "-b", "main")
    git(repo, "config", "user.name", "Fixture")
    git(repo, "config", "user.email", "fixture@example.invalid")
    git(repo, "config", "core.autocrlf", "false")
    excludes = repo.parent / "empty-excludes"
    excludes.touch()
    git(repo, "config", "core.excludesFile", excludes.as_posix())


class TokenHygieneTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.root = ROOT / "dist" / f"token-hygiene-tests-{uuid.uuid4().hex}"
        cls.root.mkdir(parents=True)
        cls.addClassCleanup(remove_fixture, cls.root)
        clone_temp = cls.root / "clone-temp"
        clone_temp.mkdir()
        global_config = cls.root / "empty-gitconfig"
        global_config.touch()
        cls.env = dict(os.environ, TEMP=str(clone_temp), TMP=str(clone_temp),
                       TMPDIR=clone_temp.as_posix(), GIT_CONFIG_NOSYSTEM="1",
                       GIT_CONFIG_GLOBAL=global_config.as_posix())
        for key in ("SHEEN_REPO", "SHEEN_REF", "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE"):
            cls.env.pop(key, None)
        cls.upstream = cls.root / "upstream"
        init(cls.upstream)
        write(cls.upstream, "tokens/fixture.json", '{"fixture": "source token payload"}\n')
        write(cls.upstream, "templates/fixture.txt", "source template\n")
        write(cls.upstream, "scripts/build-tokens.ps1", """param([string]$TokensDir, [string]$OutDir)
$ErrorActionPreference = 'Stop'
if (-not [System.IO.File]::Exists((Join-Path $TokensDir 'fixture.json'))) { throw 'Missing token source' }
[void][System.IO.Directory]::CreateDirectory($OutDir)
foreach ($name in @('sheen.css', 'sheen.js', 'sheen.esm.js', 'sheen.d.ts')) {
    $header = if ($name -eq 'sheen.css') { "/* $name — generated by scripts/build-tokens.ps1; do not hand-edit */" } else { "// $name — generated by scripts/build-tokens.ps1; do not hand-edit" }
    [System.IO.File]::WriteAllText((Join-Path $OutDir $name), "$header`nregenerated $name`n")
}
""")
        git(cls.upstream, "add", "-A")
        git(cls.upstream, "commit", "--quiet", "-m", "Minimal local upstream")
        probe = run(["pwsh", "-NoProfile", "-NonInteractive", "-Command",
                     "if (Get-Command ConvertFrom-Yaml -ErrorAction SilentlyContinue) { exit 0 }; exit 3"],
                    ROOT, cls.env, check=False)
        if probe.returncode not in (0, 3):
            raise AssertionError(probe.stdout + probe.stderr)
        cls.launcher = cls.root / "run-sync.ps1"
        shim = ""
        if probe.returncode == 3:
            print("Boundary: powershell-yaml absent; strict fixture-only scalar decoder enabled.", flush=True)
            shim = r"""
function ConvertFrom-Yaml {
    param([Parameter(ValueFromPipeline)][string]$Yaml)
    process {
        $result = @{}
        foreach ($line in ($Yaml -split "`n")) {
            if (-not $line.Trim()) { continue }
            if ($line -notmatch '^(source|ref|materialize_tokens): (.+)$') {
                throw "Unsupported fixture config: $line"
            }
            $result[$Matches[1]] = $Matches[2].Trim()
        }
        return $result
    }
}
"""
        else:
            print("Boundary: real ConvertFrom-Yaml available; no config shim.", flush=True)
        # Keep real terminating diagnostics stable across host ANSI/line-wrap formatting.
        cls.launcher.write_text(shim + """
try { & $args[0] }
catch {
    [Console]::Error.WriteLine($_.Exception.Message)
    exit 1
}
""", encoding="utf-8")
        cls.mutants = {}
        for engine, invocation in (("ps1", "            Protect-GeneratedTokens\n"),
                                   ("sh", "    protect_generated_tokens\n")):
            source = (ROOT / f"sync.{engine}").read_text(encoding="utf-8")
            if source.count(invocation) != 1:
                raise AssertionError("Negative mutation must remove exactly one real hygiene invocation")
            mutant = cls.root / f"old-behavior-sync.{engine}"
            mutant.write_text(source.replace(invocation, ""), encoding="utf-8", newline="\n")
            cls.mutants[engine] = mutant

    def consumer(self, ignore=None, nested=None, tracked=False, enabled=True):
        repo = self.root / f"consumer-{uuid.uuid4().hex}"
        init(repo)
        write(repo, ".sheen.yml", f"source: {self.upstream.as_posix()}\nref: main\n"
              f"materialize_tokens: {str(enabled).lower()}\n")
        for name in SENTINELS:
            write(repo, name, f"untouched {name}\n")
        if ignore is not None:
            write(repo, ".gitignore", ignore)
        if nested is not None:
            write(repo, "dist/tokens/.gitignore", nested)
        if tracked:
            for name in OUTPUTS:
                write(repo, name, generated(name))
        git(repo, "add", "-f", ".")
        git(repo, "commit", "--quiet", "-m", "Consumer-owned baseline")
        # Untracked unrelated output must still participate in git add -A.
        write(repo, "dist/tokens/unrelated-new.js", "consumer output\n")
        return repo

    def sync(self, repo, engine, mutant=False, expected=0):
        script = self.mutants[engine] if mutant else ROOT / f"sync.{engine}"
        args = (["pwsh", "-NoProfile", "-NonInteractive", "-File", str(self.launcher), str(script)]
                if engine == "ps1" else [BASH, script.as_posix()])
        result = run(args, repo, self.env, check=False)
        self.assertEqual(result.returncode, expected, result.stdout + result.stderr)
        return result.stdout + result.stderr

    def assert_preserved(self, repo):
        for name in SENTINELS:
            self.assertEqual((repo / name).read_text(), f"untouched {name}\n")
        self.assertEqual((repo / "sheen/tokens/fixture.json").read_bytes(),
                         (self.upstream / "tokens/fixture.json").read_bytes())
        self.assertEqual((repo / "sheen/templates/fixture.txt").read_text(), "source template\n")
        files = json.loads((repo / ".sheen/manifest.json").read_text(encoding="utf-8-sig"))["files"]
        self.assertIn("sheen/tokens/fixture.json", files)
        self.assertIn("sheen/templates/fixture.txt", files)
        self.assertNotIn(".gitignore", files)
        self.assertTrue(set(OUTPUTS).isdisjoint(files))
        for name in OUTPUTS:
            self.assertEqual((repo / name).read_text(encoding="utf-8"), generated(name))

    def test_real_sync_scenarios(self):
        scenarios = [
            ("missing", None, None, set(), False),
            ("empty", b"", None, set(), False),
            ("existing-partial", b"# app\n*.log\n/dist/tokens/sheen.css\n", None, set(), False),
            ("crlf-bom-no-final-newline", b"\xef\xbb\xbf# consumer\r\n*.log", None, set(), False),
            ("lf-no-final-newline", b"# keep this byte prefix", None, set(), False),
            ("broad", b"# already covered\ndist/\n", None, set(), False),
            ("exact", RULES, None, set(), False),
            ("negated-all", RULES + b"!/dist/tokens/sheen.*\n", None, set(OUTPUTS), False),
            ("negated-one", b"!/dist/tokens/sheen.css\n", None, {OUTPUTS[0]}, False),
            ("nested-override", b"/dist/tokens/*\n", b"!sheen.css\n", {OUTPUTS[0]}, False),
            ("nested-only", None, b"!sheen.js\n", {OUTPUTS[1]}, False),
            ("tracked", None, None, set(), True),
            ("tracked-bom-crlf", None, None, set(), True),
            ("tracked-broad", b"dist/\n", None, set(), True),
            ("tracked-nested-included", b"/dist/tokens/*\n", b"!sheen.css\n", {OUTPUTS[0]}, True),
            ("tracked-included", RULES + b"!/dist/tokens/sheen.*\n", None, set(OUTPUTS), True),
        ]
        for engine in ("ps1", "sh"):
            for label, ignore, nested, included, tracked in scenarios:
                with self.subTest(engine=engine, scenario=label):
                    repo = self.consumer(ignore, nested, tracked)
                    if label == "tracked-bom-crlf":
                        for path in OUTPUTS:
                            write(repo, path, b"\xef\xbb\xbf" + generated(path, "obsolete output\n").replace("\n", "\r\n").encode())
                        git(repo, "add", *OUTPUTS)
                        git(repo, "commit", "--quiet", "-m", "Old generated output with BOM and CRLF")
                    # Existing unrelated staged and unstaged edits must survive cleanup.
                    write(repo, "consumer-staged.txt", "keep staged\n")
                    git(repo, "add", "consumer-staged.txt")
                    write(repo, "consumer-unstaged.txt", "keep unstaged\n")
                    index_before = (repo / ".git/index").read_bytes()
                    entries_before = index_entries(repo)
                    log = self.sync(repo, engine)
                    removed = set(OUTPUTS) - included if tracked else set()
                    self.assertEqual(index_entries(repo), {p: entry for p, entry in entries_before.items()
                                                          if p not in removed})
                    if not removed:
                        self.assertEqual((repo / ".git/index").read_bytes(), index_before)
                    self.assertEqual(set(git(repo, "diff", "--cached", "--name-only", "--diff-filter=D").splitlines()),
                                     removed)
                    self.assertNotIn("consumer-unstaged.txt", index_entries(repo))
                    self.assert_preserved(repo)
                    after = (repo / ".gitignore").read_bytes() if (repo / ".gitignore").exists() else None
                    if ignore is not None:
                        self.assertTrue(after.startswith(ignore))
                    if label in ("broad", "exact", "negated-all", "nested-override", "tracked-included",
                                 "tracked-broad", "tracked-nested-included"):
                        self.assertEqual(after, ignore)
                    if label == "missing":
                        self.assertEqual(after, RULES)
                    if label == "crlf-bom-no-final-newline":
                        self.assertEqual(after, ignore + b"\r\n" + RULES.replace(b"\n", b"\r\n"))
                    if label == "lf-no-final-newline":
                        self.assertEqual(after, ignore + b"\n" + RULES)
                    if nested is not None:
                        self.assertEqual((repo / "dist/tokens/.gitignore").read_bytes(), nested)
                    for path in OUTPUTS:
                        result = run(["git", "check-ignore", "--no-index", "--quiet", "--", path],
                                     repo, self.env, check=False)
                        self.assertEqual(result.returncode, 1 if path in included else 0, path)
                        if path in included:
                            self.assertIn(f"preserving explicit Git inclusion for {path}", log)
                            verbose = run(["git", "check-ignore", "--no-index", "--verbose", "--", path],
                                          repo, self.env, check=False)
                            self.assertEqual(verbose.returncode, 0, "Verbose negation is success, not ignored")
                    if removed:
                        self.assertIn("staged deletion of obsolete generated token outputs", log)
                    entries_after = index_entries(repo)
                    for path in OUTPUTS:
                        if not tracked or path in removed:
                            write(repo, path, generated(path, "stale output: repeat must rebuild even when ignored\n"))
                    self.sync(repo, engine)
                    self.assertEqual((repo / ".gitignore").read_bytes(), after)
                    self.assertEqual(index_entries(repo), entries_after)
                    self.assert_preserved(repo)
                    self.assertEqual((repo / "consumer-staged.txt").read_text(), "keep staged\n")
                    self.assertEqual((repo / "consumer-unstaged.txt").read_text(), "keep unstaged\n")
                    self.assertEqual(run(["git", "check-ignore", "--no-index", "--quiet", "--",
                                          "app/dist/tokens/sheen.css"], repo, self.env,
                                         check=False).returncode, 0 if label in ("broad", "tracked-broad") else 1,
                                     "New rules must be root-anchored; consumer's broad rule stays effective")
                    git(repo, "add", "-A")
                    staged = set(git(repo, "diff", "--cached", "--name-only").splitlines())
                    self.assertEqual(staged.intersection(OUTPUTS), removed if tracked else included)
                    self.assertEqual(set(git(repo, "diff", "--cached", "--name-only", "--diff-filter=D").splitlines()),
                                     removed, "git add -A must not resurrect deleted generated remnants")
                    if after != ignore:
                        self.assertIn(".gitignore", staged, "Consumer workflow must stage new rules")
                    if label not in ("broad", "nested-override", "tracked-broad", "tracked-nested-included"):
                        self.assertIn("dist/tokens/unrelated-new.js", staged)
                    print(f"PASS {engine}: {label}; {len(removed)} staged deletions, unrelated index preserved, repeat stable", flush=True)

    def test_conflicting_edits_and_unknown_ownership_fail_without_token_changes(self):
        for engine in ("ps1", "sh"):
            for kind in ("unstaged", "unstaged-deletion", "staged", "staged-addition", "tracked-custom",
                         "untracked-custom", "included-dirty"):
                with self.subTest(engine=engine, scenario=kind):
                    repo = self.consumer(ignore=RULES + b"!/dist/tokens/sheen.*\n"
                                         if kind == "included-dirty" else None,
                                         tracked=kind not in ("untracked-custom", "staged-addition"))
                    path = OUTPUTS[-1]  # Last file proves all outputs preflight before any removal.
                    if kind in ("tracked-custom", "untracked-custom"):
                        write(repo, path, "hand-authored collision: preserve me\n")
                    else:
                        write(repo, path, generated(path, "important edited work\n"))
                    if kind == "unstaged-deletion":
                        (repo / path).unlink()
                    if kind in ("staged", "staged-addition", "tracked-custom"):
                        git(repo, "add", path)
                    if kind == "tracked-custom":
                        git(repo, "commit", "--quiet", "-m", "Consumer custom output")
                    write(repo, "unrelated-staged.txt", "preserve unrelated staged addition\n")
                    git(repo, "add", "unrelated-staged.txt")
                    before = (repo / ".git/index").read_bytes()
                    contents = {p: (repo / p).read_bytes() if (repo / p).exists() else None for p in OUTPUTS}
                    ignore_before = (repo / ".gitignore").read_bytes() if (repo / ".gitignore").exists() else None
                    log = self.sync(repo, engine, expected=1)
                    self.assertIn("token cleanup blocked", log)
                    self.assertNotIn("running token build", log)
                    self.assertEqual((repo / ".git/index").read_bytes(), before)
                    self.assertEqual((repo / ".gitignore").read_bytes() if (repo / ".gitignore").exists() else None,
                                     ignore_before)
                    for path, content in contents.items():
                        self.assertEqual((repo / path).read_bytes() if (repo / path).exists() else None, content)
                    print(f"PASS {engine}: {kind}; visible failure, no output/index/ignore changes", flush=True)

    def test_index_flags_fail_closed_even_when_diff_hides_edits(self):
        flag_sets = (
            (("--assume-unchanged",), "h", "assume-unchanged"),
            (("--skip-worktree",), "S", "skip-worktree"),
            (("--assume-unchanged", "--skip-worktree"), "s", "assume-unchanged, skip-worktree"),
        )
        for engine in ("ps1", "sh"):
            for flags, tag, description in flag_sets:
                for state in ("clean", "hidden-edit", "included-hidden-edit"):
                    with self.subTest(engine=engine, flags=description, state=state):
                        ignore = RULES + b"!/dist/tokens/sheen.*\n" if state == "included-hidden-edit" else None
                        repo = self.consumer(ignore=ignore, tracked=True)
                        path = OUTPUTS[-1]
                        original = (repo / path).read_bytes()
                        for flag in flags:
                            git(repo, "update-index", flag, "--", path)
                        self.assertEqual(git(repo, "ls-files", "-v", "--", path).strip(), f"{tag} {path}")
                        if state != "clean":
                            write(repo, path, generated(path, "hidden local edits: never overwrite\n"))
                            self.assertNotEqual((repo / path).read_bytes(), original)
                        # Reproduce the review finding: native Git reports clean even with hidden edits.
                        self.assertEqual(run(["git", "diff", "--quiet", "--", path], repo, self.env,
                                             check=False).returncode, 0)
                        write(repo, "unrelated-staged.txt", "preserve unrelated staged addition\n")
                        git(repo, "add", "unrelated-staged.txt")
                        before = (repo / ".git/index").read_bytes()
                        flagged_before = git(repo, "ls-files", "-v")
                        contents = {p: (repo / p).read_bytes() for p in OUTPUTS}
                        log = self.sync(repo, engine, expected=1)
                        self.assertIn(f"token cleanup blocked by index flags ({description}): {path}", log)
                        self.assertNotIn("running token build", log)
                        self.assertEqual((repo / ".git/index").read_bytes(), before)
                        self.assertEqual(git(repo, "ls-files", "-v"), flagged_before)
                        self.assertEqual((repo / ".gitignore").read_bytes() if (repo / ".gitignore").exists() else None,
                                         ignore)
                        for output, content in contents.items():
                            self.assertEqual((repo / output).read_bytes(), content)
                        self.assertEqual((repo / "unrelated-staged.txt").read_text(),
                                         "preserve unrelated staged addition\n")
                        print(f"PASS {engine}: {description}, {state}; flags/index/output/ignore preserved", flush=True)

    @unittest.skipIf(os.name == "nt", "Unix FIFO and symlink integration runs in native Linux CI")
    def test_unix_nonregular_outputs_fail_before_open_or_mutation(self):
        for engine in ("ps1", "sh"):
            for kind in ("fifo", "symlink", "dangling-symlink", "directory"):
                with self.subTest(engine=engine, kind=kind):
                    repo = self.consumer(tracked=True)
                    path = OUTPUTS[-1]
                    output = repo / path
                    git(repo, "rm", "--", path)
                    git(repo, "commit", "--quiet", "-m", "Untracked collision fixture")
                    if kind == "fifo":
                        os.mkfifo(output)
                    elif kind == "directory":
                        output.mkdir()
                    else:
                        target = repo / "link-target"
                        if kind == "symlink":
                            target.write_bytes(b"unrelated link target: preserve")
                        output.symlink_to(target)
                    write(repo, "unrelated-staged.txt", "preserve staged work\n")
                    git(repo, "add", "unrelated-staged.txt")
                    before = (repo / ".git/index").read_bytes()
                    output_before = output.lstat()
                    contents = {p: (repo / p).read_bytes() for p in OUTPUTS[:-1]}
                    log = self.sync(repo, engine, expected=1)
                    self.assertIn(f"token cleanup blocked by non-regular output: {path}", log)
                    self.assertNotIn("running token build", log)
                    self.assertEqual((repo / ".git/index").read_bytes(), before)
                    self.assertFalse((repo / ".gitignore").exists())
                    self.assertEqual(output.lstat().st_mode, output_before.st_mode)
                    self.assertEqual(output.lstat().st_ino, output_before.st_ino)
                    for other, content in contents.items():
                        self.assertEqual((repo / other).read_bytes(), content)
                    if kind in ("symlink", "dangling-symlink"):
                        self.assertEqual(os.readlink(output), str(target))
                        if kind == "symlink":
                            self.assertEqual(target.read_bytes(), b"unrelated link target: preserve")
                        else:
                            self.assertFalse(target.exists())
                    print(f"PASS {engine}: Unix {kind}; no open/blocking, index/output/ignore preserved",
                          flush=True)

    def test_disabled_does_not_edit_ignore_or_build(self):
        for engine in ("ps1", "sh"):
            for ignore in (None, b"\xef\xbb\xbf# consumer\r\n*.log"):
                with self.subTest(engine=engine, ignore=ignore):
                    repo = self.consumer(ignore, enabled=False)
                    before = (repo / ".git/index").read_bytes()
                    self.sync(repo, engine)
                    path = repo / ".gitignore"
                    self.assertEqual(path.read_bytes() if path.exists() else None, ignore)
                    self.assertFalse((repo / "scripts/build-tokens.ps1").exists())
                    self.assertFalse(any((repo / path).exists() for path in OUTPUTS))
                    self.assertEqual((repo / ".git/index").read_bytes(), before)
                    print(f"PASS {engine}: disabled, {'existing' if ignore else 'missing'} ignore untouched", flush=True)

    def test_old_behavior_accidentally_stages_outputs(self):
        for engine in ("ps1", "sh"):
            with self.subTest(engine=engine):
                repo = self.consumer()
                self.sync(repo, engine, mutant=True)
                self.assertFalse((repo / ".gitignore").exists())
                git(repo, "add", "-A")
                staged = set(git(repo, "diff", "--cached", "--name-only").splitlines())
                self.assertTrue(set(OUTPUTS).issubset(staged))
                print(f"PASS {engine}: old-behavior mutation reproduces all four accidental staged outputs", flush=True)


if __name__ == "__main__":
    unittest.main(verbosity=2)
